# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_coinpayments', '0002_auto_20180428_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency_original',
            field=models.CharField(choices=[(b'BCH', b'Bitcoin Cash'), (b'BLK', b'BlackCoin'), (b'BTC', b'Bitcoin'), (b'DASH', b'Dash'), (b'DCR', b'Decred'), (b'DGB', b'DigiByte'), (b'DOGE', b'Dogecoin'), (b'ETC', b'Ether Classic'), (b'ETH', b'Ether'), (b'EOS', b'EOS'), (b'EXP', b'Expanse'), (b'GAME', b'GameCredits'), (b'LSK', b'LISK'), (b'LTC', b'Litecoin'), (b'MAID', b'MaidSafeCoin'), (b'NAV', b'NAV Coin'), (b'NEO', b'NEO'), (b'POT', b'PotCoin'), (b'SBD', b'Steem Dollars'), (b'STEEM', b'STEEM'), (b'STRAT', b'Stratis'), (b'VTC', b'Vertcoin'), (b'XEM', b'NEM'), (b'XMR', b'Monero'), (b'XRP', b'Ripple'), (b'XVG', b'VERGE')], max_length=8, verbose_name='Original currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency_paid',
            field=models.CharField(choices=[(b'BCH', b'Bitcoin Cash'), (b'BLK', b'BlackCoin'), (b'BTC', b'Bitcoin'), (b'DASH', b'Dash'), (b'DCR', b'Decred'), (b'DGB', b'DigiByte'), (b'DOGE', b'Dogecoin'), (b'ETC', b'Ether Classic'), (b'ETH', b'Ether'), (b'EOS', b'EOS'), (b'EXP', b'Expanse'), (b'GAME', b'GameCredits'), (b'LSK', b'LISK'), (b'LTC', b'Litecoin'), (b'MAID', b'MaidSafeCoin'), (b'NAV', b'NAV Coin'), (b'NEO', b'NEO'), (b'POT', b'PotCoin'), (b'SBD', b'Steem Dollars'), (b'STEEM', b'STEEM'), (b'STRAT', b'Stratis'), (b'VTC', b'Vertcoin'), (b'XEM', b'NEM'), (b'XMR', b'Monero'), (b'XRP', b'Ripple'), (b'XVG', b'VERGE')], max_length=8, verbose_name='Payment currency'),
        ),
    ]
